version: '3.8'

services:
  # Servicio PHP + Apache
  app:
    build: .
    container_name: app_php
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # Servicio MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crud_empleados
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - volumen_mysql:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  # Servicio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_ROOT_PASSWORD: 1234

volumes:
  volumen_mysql:
